# Generated by Django 3.1.7 on 2021-05-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_auto_20210508_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
