# Generated by Django 3.1.7 on 2021-05-10 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_auto_20210508_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='registerID',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
